version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092
    networks:
      - urls-scraper

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
      - urls-scraper

  app:
    build: .
    volumes:
      - ./:/app
    networks:
      - urls-scraper
    depends_on:
      - kafka
      - mongo
    command: ["python3", "main.py", "--producer=1"]

networks:
  urls-scraper:
    driver: bridge
