version: '3.8'

services:
  kafka:
    image: apache/kafka:3.9.0
    volumes:
      - kafka_data:/var/lib/kafka/data
    ports:
      - 9092:9092
    networks:
      - links-scraper

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: links_scraper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - links-scraper

networks:
  links-scraper:
    driver: bridge

volumes:
  postgres_data:
  kafka_data:
