services:
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_PLAINTEXT_PORT: 9092
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_NAMES: PLAINTEXT
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - links-scraper

  postgres:
    image: postgres:15.8-alpine3.20
    environment:
      POSTGRES_DB: links_scraper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - links-scraper

networks:
  links-scraper:
    driver: bridge

volumes:
  postgres_data:
  kafka_data:
